### ISSUE TITLE
Not launching game

### ISSUE THREAD

**Issue by NotTerrorXD** [BlazeClient/BlazeClient-mod#5]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2024-12-13 21:34:26
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'indium' at 'link.infra.indium.Indium'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:487)
	at knot//net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at knot//net.minecraft.class_4668.<clinit>(class_4668.java:126)
	at knot//net.fabricmc.fabric.api.renderer.v1.material.BlendMode.<clinit>(BlendMode.java:33)
	at knot//link.infra.indium.renderer.material.MaterialViewImpl.<clinit>(MaterialViewImpl.java:31)
	at knot//link.infra.indium.renderer.IndiumRenderer.materialFinder(IndiumRenderer.java:49)
	at knot//link.infra.indium.renderer.IndiumRenderer.<clinit>(IndiumRenderer.java:32)
	at knot//link.infra.indium.Indium.onInitializeClient(Indium.java:117)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_757 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 13 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 17 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector changeHurtCamType(Lnet/minecraft/class_1309;)F in blaze-client.mixins.json:GameRendererMixin from mod blaze-client failed injection check, (0/1) succeeded. Scanned 0 target(s). Using refmap Blaze-1.20.4-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:531)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1490)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:752)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:330)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:246)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:437)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:418)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 20 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:487)

-- Initialization --
Details:
	Modules: 
		ADVAPI32.dll:Advanced Windows 32 Base API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		COMCTL32.dll:Common Controls Library:5.82 (WinBuild.160101.0800):Microsoft Corporation
		CRYPT32.dll:Crypto API32:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTBASE.dll:Base cryptographic API DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		CRYPTSP.dll:Cryptographic Service Provider API:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		DBGHELP.DLL:Windows Image Helper:10.0.26100.2033 (WinBuild.160101.0800):Microsoft Corporation
		DNSAPI.dll:DNS Client API DLL:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		GDI32.dll:GDI Client DLL:10.0.26100.2033 (WinBuild.160101.0800):Microsoft Corporation
		IMM32.DLL:Multi-User Windows IMM32 API Client DLL:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		IPHLPAPI.DLL:IP Helper API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		KERNEL32.DLL:Windows NT BASE API Client DLL:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		KERNELBASE.dll:Windows NT BASE API Client DLL:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		MSVCP140.dll:Microsoft® C Runtime Library:14.36.32532.0:Microsoft Corporation
		MinecraftJava.exe
		MpOav.dll:IOfficeAntiVirus Module:4.18.24090.11 (26d75470953920f90fd0438874501e9d9a31e621):Microsoft Corporation
		NSI.dll:NSI User-mode interface DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		NTASN1.dll:Microsoft ASN.1 API:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		OLEAUT32.dll:OLEAUT32.DLL:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		Ole32.dll:Microsoft OLE for Windows:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		POWRPROF.dll:Power Profile Helper DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		PSAPI.DLL:Process Status Helper:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		Pdh.dll:Windows Performance Data Helper DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		RPCRT4.dll:Remote Procedure Call Runtime:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		SHCORE.dll:SHCORE:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		SHELL32.dll:Windows Shell Common Dll:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		UMPDC.dll:User Mode Power Dependency Coordinator:10.0.26100.1301 (WinBuild.160101.0800):Microsoft Corporation
		USER32.dll:Multi-User Windows USER API Client DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		USERENV.dll:Userenv:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		VCRUNTIME140.dll:Microsoft® C Runtime Library:14.36.32532.0:Microsoft Corporation
		VCRUNTIME140_1.dll:Microsoft® C Runtime Library:14.36.32532.0:Microsoft Corporation
		VERSION.dll:Version Checking and File Installation Libraries:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		WINHTTP.dll:Windows HTTP Services:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		WINMM.dll:MCI API DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		WS2_32.dll:Windows Socket 2.0 32-Bit DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		WSOCK32.dll:Windows Socket 32-Bit DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		amsi.dll:Anti-Malware Scan Interface:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		apphelp.dll:Application Compatibility Client Library:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		awt.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		bcrypt.dll:Windows Cryptographic Primitives Library:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		bcryptPrimitives.dll:Windows Cryptographic Primitives Library:10.0.26100.2033 (WinBuild.160101.0800):Microsoft Corporation
		clbcatq.dll:COM+ Configuration Catalog:2001.12.10941.16384 (WinBuild.160101.0800):Microsoft Corporation
		combase.dll:Microsoft COM for Windows:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		dbgcore.DLL:Windows Core Debugging Helpers:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc.DLL:DHCP Client Service:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		dhcpcsvc6.DLL:DHCPv6 Client:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		discord-rpc.dll
		fwpuclnt.dll:FWP/IPsec User-Mode API:10.0.26100.2161 (WinBuild.160101.0800):Microsoft Corporation
		gdi32full.dll:GDI Client DLL:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		glfw.dll:GLFW 3.4.0 DLL:3.4.0:GLFW
		instrument.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		java.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jemalloc.dll
		jimage.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jli.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jna17552729810286989323.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
		jna2388527055636318063.dll:JNA native library:6.1.6:Java(TM) Native Access (JNA)
		jsvml.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		jvm.dll:OpenJDK 64-Bit server VM:17.0.8.0:Microsoft
		kernel.appcore.dll:AppModel API Host:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		lwjgl.dll
		management.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		management_ext.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		msvcp140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		msvcp_win.dll:Microsoft® C Runtime Library:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		msvcrt.dll:Windows NT CRT DLL:7.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		mswsock.dll:Microsoft Windows Sockets 2.0 Service Provider:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		napinsp.dll:E-mail Naming Shim Provider:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		ncrypt.dll:Windows NCrypt Router:10.0.26100.1591 (WinBuild.160101.0800):Microsoft Corporation
		net.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nio.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		nlansp_c.dll:NLA Namespace Service Provider DLL:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		ntdll.dll:NT Layer DLL:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		perfos.dll:Windows System Performance Objects DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		pfclient.dll:SysMain Client:10.0.26100.1301 (WinBuild.160101.0800):Microsoft Corporation
		profapi.dll:User Profile Basic API:10.0.26100.2454 (WinBuild.160101.0800):Microsoft Corporation
		rasadhlp.dll:Remote Access AutoDial Helper:10.0.26100.1150 (WinBuild.160101.0800):Microsoft Corporation
		rsaenh.dll:Microsoft Enhanced Cryptographic Provider:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		sechost.dll:Host for SCM/SDDL/LSA Lookup APIs:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		shlwapi.dll:Shell Light-weight Utility Library:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		sunmscapi.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		ucrtbase.dll:Microsoft® C Runtime Library:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		vcruntime140.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		vcruntime140_1.dll:Microsoft® C Runtime Library:14.29.30139.0 built by: vcwrkspc:Microsoft Corporation
		verify.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
		win32u.dll:Win32u:10.0.26100.2605 (WinBuild.160101.0800):Microsoft Corporation
		windows.storage.dll:Microsoft WinRT Storage API:10.0.26100.1457 (WinBuild.160101.0800):Microsoft Corporation
		winrnr.dll:LDAP RnR Provider DLL:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		wshbth.dll:Windows Sockets Helper DLL:10.0.26100.1882 (WinBuild.160101.0800):Microsoft Corporation
		wshunix.dll:AF_UNIX Winsock2 Helper DLL:10.0.26100.1 (WinBuild.160101.0800):Microsoft Corporation
		zip.dll:OpenJDK Platform binary:17.0.8.0:Microsoft
Stacktrace:
	at knot//net.minecraft.client.main.Main.main(Main.java:223)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.20.4
	Minecraft Version ID: 1.20.4
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 320624448 bytes (305 MiB) / 620756992 bytes (592 MiB) up to 6979321856 bytes (6656 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz
	Identifier: Intel64 Family 6 Model 126 Stepping 5
	Microarchitecture: Ice Lake (Client)
	Frequency (GHz): 1.19
	Number of physical packages: 1
	Number of physical CPUs: 2
	Number of logical CPUs: 4
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x8a56
	Graphics card #0 versionInfo: DriverVersion=27.20.100.7988
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: Unknown
	Virtual memory max (MB): 21193.03
	Virtual memory used (MB): 8222.46
	Swap memory total (MB): 13312.00
	Swap memory used (MB): 465.66
	JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx6656m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	Fabric Mods: 
		antighost: AntiGhost 1.20.4-fabric0.91.2-1.1.5
			crowdin-translate: CrowdinTranslate 1.4+1.19.3
		appleskin: AppleSkin 2.5.1+mc1.20.3
		badoptimizations: BadOptimizations 2.1.4
		betterhurtcam: BetterHurtCam 1.7.0+mc1.20.3
		betterpingdisplay: Better Ping Display 1.1.1
		betterthirdperson: Better Third Person 1.9.0
		blaze-client: Blaze Client 5fec861
			club_minnced_discord-rpc-release: discord-rpc-release v3.4.0
			com_github_minndevelopment_java-discord-rpc: java-discord-rpc v2.0.2
		capes: Capes 1.5.3+1.20.2
		cloth-config: Cloth Config v13 13.0.121
			cloth-basic-math: cloth-basic-math 0.6.1
		collective: Collective 7.64
		custom-crosshair-mod: Custom Crosshair Mod 1.5.6-fabric
		debugify: Debugify 1.20.4+1.1
		dynamic_fps: Dynamic FPS 3.7.7
			net_lostluma_battery: battery 1.3.0
		eatinganimationid: Eating Animation 1.20+1.9.61
		elementa: Elementa 670
		entityculling: EntityCulling 1.6.6
		essential: Essential 1.3.5.5
		essential-container: essential-container 1.0.0
			essential-loader: essential-loader 1.2.3
		fabric-api: Fabric API 0.97.1+1.20.4
			fabric-api-base: Fabric API Base 0.4.37+78d798af4f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.50+82b1bb3e4f
			fabric-biome-api-v1: Fabric Biome API (v1) 13.0.17+78d798af4f
			fabric-block-api-v1: Fabric Block API (v1) 1.0.17+3e2216cb4f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.5+78d798af4f
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.47+78d798af4f
			fabric-client-tags-api-v1: Fabric Client Tags 1.1.8+78d798af4f
			fabric-command-api-v1: Fabric Command API (v1) 1.2.42+f71b366f4f
			fabric-command-api-v2: Fabric Command API (v2) 2.2.21+78d798af4f
			fabric-commands-v0: Fabric Commands (v0) 0.2.59+df3654b34f
			fabric-containers-v0: Fabric Containers (v0) 0.1.87+df3654b34f
			fabric-content-registries-v0: Fabric Content Registries (v0) 5.0.16+78d798af4f
			fabric-convention-tags-v1: Fabric Convention Tags 1.5.11+78d798af4f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.24+78d798af4f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.1.5+b90db5744f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 13.2.5+5c0133444f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.63+6605d1a84f
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.6.2+09fc25014f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.7.2+389931eb4f
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.75+df3654b34f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.47+78d798af4f
			fabric-item-api-v1: Fabric Item API (v1) 2.3.0+bcdd12964f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.0.27+ee30b13a4f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.42+78d798af4f
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.40+df3654b34f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.3.1+a67ffb5d4f
			fabric-loot-api-v2: Fabric Loot API (v2) 2.1.10+78d798af4f
			fabric-message-api-v1: Fabric Message API (v1) 6.0.6+78d798af4f
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.66+78d798af4f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 1.0.9+78d798af4f
			fabric-models-v0: Fabric Models (v0) 0.4.8+9386d8a74f
			fabric-networking-api-v1: Fabric Networking API (v1) 3.1.8+2e5ac5484f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 13.1.0+dba1195c4f
			fabric-particles-v1: Fabric Particles (v1) 1.1.8+78d798af4f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 2.0.21+78d798af4f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 4.0.20+ee30b13a4f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 3.2.5+78d798af4f
			fabric-renderer-indigo: Fabric Renderer - Indigo 1.5.6+d331d3144f
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.54+df3654b34f
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.43+73761d2e4f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.2+e761c6694f
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.57+df3654b34f
			fabric-rendering-v1: Fabric Rendering (v1) 3.2.1+6fd945a04f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.3.15+78d798af4f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.11.21+ee30b13a4f
			fabric-screen-api-v1: Fabric Screen API (v1) 2.0.18+78d798af4f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.56+78d798af4f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.18+78d798af4f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 4.0.12+90f2d7b14f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 5.0.15+78d798af4f
		fabric-language-kotlin: Fabric Language Kotlin 1.11.0+kotlin.2.0.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 2.0.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 2.0.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.24.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.8.1
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.8.1
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.6.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.6.3
		fabricloader: Fabric Loader 0.16.7
			mixinextras: MixinExtras 0.4.1
		ferritecore: FerriteCore 6.0.3
		forcecloseworldloadingscreen: kennytv's epic force close loading screen mod for Fabric 2.2.1
		fpsdisplay: FPS-Display 4.0.1+1.20.4
		gammautils: Gamma Utils 1.7.19
		healthindicators: Health Indicators 2.5.3-beta
		ias: In-Game Account Switcher 9.0.0
		immediatelyfast: ImmediatelyFast 1.2.18+1.20.4
			net_lenni0451_reflect: Reflect 1.3.4
		indium: Indium 1.0.31+mc1.20.4
		iris: Iris 1.7.0+mc1.20.4
			io_github_douira_glsl-transformer: glsl-transformer 2.0.0-pre13
			org_anarres_jcpp: jcpp 1.4.14
			org_antlr_antlr4-runtime: antlr4-runtime 4.11.1
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.2.6
			com_velocitypowered_velocity-native: velocity-native 3.2.0-SNAPSHOT
		lithium: Lithium 0.12.1
		memoryleakfix: Memory Leak Fix 1.1.5
		minecraft: Minecraft 1.20.4
		modmenu: Mod Menu 9.2.0
			placeholder-api: Placeholder API 2.4.0-pre.1+1.20.4
		morecosmetics: MoreCosmetics 1.2
		moreculling: More Culling 1.20.4-0.24.0
			conditional-mixin: conditional mixin 0.3.2
			mixinsquared: MixinSquared 0.1.1
		mousetweaks: Mouse Tweaks 2.26
		nametagping: NameTagPing 1.2
		nochatreports: No Chat Reports 1.20.4-v2.6.1
		notenoughanimations: NotEnoughAnimations 1.8.2
		org_jetbrains_annotations: annotations 23.0.0
		shulkerboxtooltip: Shulker Box Tooltip 4.1.0+1.20.4
		simple-armor-hud: Simple armor hud 1.20.4-1.4.1
			spruceui: SpruceUI 5.0.3+1.20.2
		sodium: Sodium 0.5.8+mc1.20.4
		sodium-extra: Sodium Extra 0.5.4+mc1.20.4-build.116
			caffeineconfig: CaffeineConfig 1.3.0+1.17
		starlight: Starlight 1.1.3+fabric.f5dcd1a
		statuseffecttimer: Status Effect Timer 1.2.0+1.20
		threadtweak: ThreadTweak 1.20.4-0.1.2
		totemcounter: TotemCounter 1.4.1+mc1.20.3
		ukulib: ukulib 1.1.2+1.20.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		universalcraft: UniversalCraft 365
		vigilance: Vigilance 306
		vmp: Very Many Players 0.2.0+beta.7.139
			com_ibm_async_asyncutil: asyncutil 0.1.0
		waveycapes: WaveyCapes 1.4.12
		whoami: Who am I? 1.0
		whyamionfire: Why Am I on Fire? 1.3.1
		yet_another_config_lib_v3: YetAnotherConfigLib 3.5.0+1.20.4-fabric
			com_twelvemonkeys_common_common-image: common-image 3.10.0
			com_twelvemonkeys_common_common-io: common-io 3.10.0
			com_twelvemonkeys_common_common-lang: common-lang 3.10.0
			com_twelvemonkeys_imageio_imageio-core: imageio-core 3.10.0
			com_twelvemonkeys_imageio_imageio-metadata: imageio-metadata 3.10.0
			com_twelvemonkeys_imageio_imageio-webp: imageio-webp 3.10.0
			org_quiltmc_parsers_gson: gson 0.2.1
			org_quiltmc_parsers_json: json 0.2.1
		zoomify: Zoomify 2.14.0+1.20.4
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.5.1
	Launched Version: fabric-loader-0.16.7-1.20.4
	Launcher name: java-minecraft-launcher
	Backend library: LWJGL version 3.3.2-snapshot
	Backend API: Unknown
	Window size: <not initialized>
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'Blaze Client'
	Universe: 404
	Type: Client (map_client.txt)
	Locale: en_US
	CPU: <unknown>                                                                                       this is the error tell me why
this is happening im playing in fabric 1.20.4 also

**Comment by newor0599** [comment]
i think indium is the one making the game unable to launch?
